# Generated by Django 5.1.5 on 2025-01-31 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linked_student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'School'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=200)),
                ('achieved_on', models.DateTimeField(auto_now_add=True)),
                ('linked_student_id', models.IntegerField()),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='acheivements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
