# Generated by Django 5.1.5 on 2025-01-31 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbcs', '0003_remove_customuser_school_alter_achievements_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
