# Generated by Django 5.1.5 on 2025-01-31 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbcs', '0004_alter_schools_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='linked_student_id',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='acheivements', to='rbcs.students'),
        ),
    ]
