# Generated by Django 5.1.5 on 2025-01-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbcs', '0005_remove_customuser_linked_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acheivements', to='rbcs.students'),
        ),
    ]
