# Generated by Django 5.1.5 on 2025-02-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbcs', '0006_alter_achievements_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='newus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=250)),
            ],
        ),
    ]
